version: '3.8'

services:
  frontend:
    build: ./frontend/
    ports:
       - "3007:80"

  backend:
    build: ./backend/
    ports:
       - "3008:3001"
    environment:
       - DB_HOST=db
       - DB_PORT=5432
       - DB_USER=operator
       - DB_PASSWORD=operator
       - DB_NAME=postgres

    depends_on:
       - db

  db:
    image: postgres:latest
    environment:
       - POSTGRES_USER=operator
       - POSTGRES_PASSWORD=operator
       - POSTGRES_DB=postgres

    volumes:
       - pg-data:/var/lib/postgresql/data

volumes:
    pg-data:
